### ISSUE TITLE
Readme link

### ISSUE THREAD

**Issue by Louismousine** [wyattscarpenter/quiplibre#1]
The HappyFunTimes link in the readme redirects to an unknown page. Happyfuntimes seems discontinued.  Can this game still be played another way?

**Comment by pucgenie** [comment]
Do you mean the link in "How to connect controllers"? It's some clever redirector that only works when your controller device is in the same network as the device hosting the game.
See https://docs.happyfuntimes.net/ if you want to get more information about that whole thing.

**Comment by wyattscarpenter** [comment]
@Louismousine, I'm not quite clear what you're asking. There are two HappyFunTimes links in the readme. The first one is http://greggman.github.io/HappyFunTimes, which redirects to http://docs.happyfuntimes.net/, which looks fine to me. The second one is http://happyfuntimes.net, which should redirect you fine so long as you are running the game on a computer on the local network (recently I am having some trouble with that, see #2, so I would be interested to know if you are also running into trouble). I'd be happy to know more if you're interested in clarifying.

**Comment by wyattscarpenter** [comment]
I expect this has been resolved with the rewrite entailed in #3
