### ISSUE TITLE
Hey, interested in working together?

### ISSUE THREAD

**Issue by michael94ellis** [wyattscarpenter/quiplibre#8]
I noticed you made a really similar app to one I just made, quibbl.in 

Let me know if you're interested in working together!

**Comment by wyattscarpenter** [comment]
Wow, cool app!

I'm not opposed to working together, but I don't know what I could offer you vis-a-vis quip apps, and I already don't foresee myself personally doing more work on quiplibre. But hey, if you think of something, let me know!

I also be happy to mention your project in this project's Readme. I guess I can just use the URL you've mentioned, but does it have a GitHub repo or something?

**Comment by michael94ellis** [comment]
Well hey, the more the merrier but I will finish it up over time at any
rate. It is not open source at the moment, I’d like to see where it goes
before publishing it that way. It’s all express js and react typescript no
data layer.
